# Generated by Django 2.0 on 2018-02-27 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.SlugField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ptitle', models.CharField(max_length=100)),
                ('discrip', models.TextField(max_length=1000)),
                ('price', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('act_price', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('color', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=1000)),
                ('brand', models.CharField(max_length=100)),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('review', models.TextField(max_length=400)),
                ('cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.Catlog')),
            ],
        ),
    ]
