# Generated by Django 2.0 on 2018-06-18 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0004_auto_20180617_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catlog',
            name='category',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
